spring.application.name=retailbillings

# ===============================
# TiDB Cloud Database
# ===============================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/retail_billing?useSSL=true&requireSSL=true&verifyServerCertificate=true
spring.datasource.username=9Szo6jXcZfmAS45.root
spring.datasource.password=DsPcVMAQI8lMx54p


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Server
# ===============================
server.port=8080